version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '3307:3306'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/runteq_graduate
    ports:
      - 3005:3000
    stdin_open: true
    tty: true
    depends_on:
      - db
volumes:
  mysql_volume: