version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '3308:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "8080:80"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3005:3000
    stdin_open: true
    tty: true
    depends_on:
      - db

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      DOMAINS: 'www.mysite.local -> http://web:3000, mysite.local -> http://web:3000'
      STAGE: local
    volumes:
      - ./https-portal:/var/lib/https-portal

volumes:
  mysql_volume: